language: node_js
node_js:
  - "8"
  - "9"
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -U postgres -a -f sql/test_install.sql
after_script:
  - psql -U postgres -a -f sql/test_uninstall.sql
